name: Auto Merge Pull Request

on:
  pull_request_review:
    types:
      - submitted

jobs:
  auto_merge:
    name: Auto Merge Pull Request
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ github.event.pull_request.number }}
