name: Create tag

on:
  workflow_dispatch:
    inputs:
      version-type:
        type: choice
        description: Tag type
        options:
          - major
          - minor
          - patch

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        fruit: [apple, pear]
        animal: [cat, dog]
        exclude:
          - animal: dog
            fruit: aaa
        include:
          - color: green
    #      - color: pink
    #        animal: cat
    #      - fruit: apple
    #        shape: circle
    #      - fruit: banana
    #      - fruit: banana
    #        animal: cat
    steps:
      - name: Print
        run: echo "${{ matrix.fruit }} - ${{ matrix.animal }} - ${{ matrix.color }} - ${{ matrix.shape }}"
      #- name: Bump version and push tag
      #  id: tag_version
      #  uses: mathieudutour/github-tag-action@v6.2
      #  with:
      #    github_token: ${{ secrets.GITHUB_TOKEN }}
      #    default_bump: ${{ inputs.version-type }}

      #- name: Create a GitHub release
      #  uses: ncipollo/release-action@v1
      #  with:
      #    tag: ${{ steps.tag_version.outputs.new_tag }}
      #    name: Release ${{ steps.tag_version.outputs.new_tag }}
      #    body: ${{ steps.tag_version.outputs.changelog }}
