name: GitHub Actions Demo

on:
  push:
    branches:
      - main
    paths-ignore:
       - '.github/**'
       
  pull_request:
    branches:
      - main
#  schedule:
#    - cron: '15 6 * * *'
  
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'INFO'
        type: choice
        options:
          - INFO
          - WARNING
          - DEBUG

jobs:
  Inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Print the input
        run: echo  The logLevel is ${{ inputs.logLevel }}
      
      - name: Get team members
        uses: tspascoal/get-user-teams-membership@v2
        id: checkUserMember
        with:
          username: ${{ github.actor }}
          organization: "nosportugal"
          team: "octats"
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
       
      - name: Belongs team
        run: echo "Teams - ${{ steps.checkUserMember.outputs }}"
        
  GitHub-Vars:
    runs-on: ubuntu-latest
    steps:
      - name: Print github vars
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Branch: ${{ github.ref }}"
          
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3.3.0
      
      - name: Print github JSON
        run: |
          echo "${{ toJSON(github) }}"
      
#      - uses: peterjgrainger/action-create-branch@v2.2.0
#        env:
#          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
#        with:
#          branch: 'github-actions-demo'
#          sha: '${{ github.event.pull_request.head.sha }}'

      - name: List files in the repository
        run: |
          echo "The repository ${{ github.repository }} contains the following files:"
          tree
