name: GitHub Actions Demo

on:
  push:
    branches:
      - main
    paths-ignore:
       - '.github/**'
       
  pull_request:
    branches:
      - main
  schedule:
    - cron: '15 6 * * *'
  
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Branch: ${{ github.ref }}"

      - uses: actions/checkout@v3.3.0
      
      - run: |
          git checkout -b newbranch
          echo "aaa" > file.txt
          git push origin newbranch

      - name: List files in the repository
        run: |
          echo "The repository ${{ github.repository }} contains the following files:"
          tree
