name: Reusable Workflow

on:
  workflow_call:
    inputs:
      who-to-greet:
        description: 'The person to greet'
        type: string
        required: true
        default: World
    outputs:
      current-time:
        description: 'The time when greeting'
        value: ${{ jobs.reusable-job.outputs.current-time }}
      current-os:
        description: 'The os when greeting'
        value: ${{ jobs.reusable-job.outputs.current-os }}

jobs:
  reusable-job:
    runs-on: ubuntu-latest
    outputs:
      current-time: ${{ steps.output-vars.outputs.current-time }}
      current-os: ${{ steps.output-vars.outputs.current-os }}
    steps:
      - name: Greet someone
        run: echo "Hello ${{ inputs.who-to-greet }}"
      - name: Set variables
        id: output-vars
        run: |
          echo "::set-output name=current-time::$(date)"
          echo "::set-output name=current-os::$(uname -o)"
